### ISSUE TITLE
[Crash] Crash in 1.19.2 alpha when hovering over a glyph

### ISSUE THREAD

**Issue by sciguyryan** [dkmk100/ArsOmega#39] opened 2023-01-22 10:59 UTC
Hi there.

While experimenting with your mod alpha, I noticed that the mod triggers a crash when hovering over one of the glyphs in JEI. I'm unable to see which one since the game window closes before I'm able to read it.

I've attached a copy of the crash report along with this report.

[crash-2023-01-22_10.57.35-client.txt](https://github.com/dkmk100/ArsOmega/files/10474219/crash-2023-01-22_10.57.35-client.txt)

**Comment by dkmk100** [comment] 2023-01-22 16:09
that's caused by the latest ars update, try downgrading to the previous version of Ars Nouveau.

I'll fix that as soon as I can.

**Comment by dkmk100** [comment] 2023-01-28 23:18
fixed with alpha 2

**Closed as completed by dkmk100** 2023-01-28 23:18 UTC
