### ISSUE TITLE
Duping with Enchant Spell

### ISSUE THREAD

**Issue by BluePiru** [dkmk100/ArsOmega#63] opened 2023-04-29 13:41 UTC
Hi, 
it is possible to dupe every stackable Item with the Enchanting Spell.

Minecraft: 1.19.2 
Forge: 43.2.8 
Ars Noveau 1.19.2-3.13.2
Ars Omega 3.0.0-alpha-4

**Comment by vibenji** [comment] 2023-04-29 20:39
With only Ars-Modpacks this doesn´t actually happen. Must be a combination with other mods that mess with enchanting i guess. ( I am from the same server this bug was found on)

**Comment by dkmk100** [comment] 2023-04-30 04:58
I can't find one, do you have more details on how it works?

**Comment by cloby0** [comment] 2023-07-17 23:46
having this issue too
Minecraft 1.19.2
Forge 43.2.14
Ars Nouveau 3.17.9
Ars Omega 3.0.1

thinking it could be apotheosis or something that does enchant stuff

**Comment by dkmk100** [comment] 2023-07-18 01:12
@cloby0 please provide your mod list, as well as explaining exactly how to make the dupe happen. It doesn't seem to happen with just ars and Omega so I'm gonna need more information

**Comment by cloby0** [comment] 2023-07-18 01:32
(https://github.com/dkmk100/ArsOmega/files/12074861/mods.txt)

you make a spell
touch -> enchant
and then point it at a stackable item that cannot be enchanted (if it can be, including bottles or apples, it wont work)

then it duplicates it (1 -> 2, 2 -> 4, etc)

**Comment by dkmk100** [comment] 2023-07-18 03:44
I have no idea what could be causing this
I confirmed again that it does not happen with just Omega

Also, in the code, I don't touch the original itemstack at all... so I have no clue how this could even happen...

Can you try doing a binary search through the non-ars mods to see if you can find which one causes the issue? 
https://www.reddit.com/r/feedthebeast/comments/evpy6r/tips_for_modpack_authors_how_to_find_misbehaving/

I'll also try... something... in the next Omega release but I have no idea what I'm trying to fix code-wise so it probably won't work

**Comment by dkmk100** [comment] 2023-07-18 03:47
also, silly question but if you relog, are the duped items still there?
@cloby0

**Comment by cloby0** [comment] 2023-07-18 03:48
i can check, ill get back to you next time i launch the pack (soon)

**Comment by dkmk100** [comment] 2023-10-01 03:51
I never got more info on this so I'm closing it, if it's still an issue then maybe someone will provide new info

**Closed as completed by dkmk100** 2023-10-01 03:51 UTC
Labels: bug, unconfirmed, missing information
